### ISSUE TITLE
Error : Cannot find module 'js'

### ISSUE THREAD

**Issue by dimitrydhondt** [mono-company/bedrock-invoice-demo#2]
I'm getting a message about module 'js' not being found.

Error: Cannot find module 'js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new View (/home/ubuntu/workspace/bedrockinvoicedemo/node_modules/express/lib/view.js:78:30)
    at EventEmitter.render (/home/ubuntu/workspace/bedrockinvoicedemo/node_modules/express/lib/application.js:569:12)
    at renderView (/home/ubuntu/workspace/bedrockinvoicedemo/core/tasks/server.js:32:7)
    at /home/ubuntu/workspace/bedrockinvoicedemo/core/tasks/server.js:73:5
    at Layer.handle [as handle_request](/home/ubuntu/workspace/bedrockinvoicedemo/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/workspace/bedrockinvoicedemo/node_modules/express/lib/router/route.js:131:13)

**Comment by Wolfr** [comment]
This also is a 404, can you check which JS file is not being loaded in your dev tools?

**Comment by Wolfr** [comment]
@dimitrydhondt Which version of node are you using?

**Comment by dimitrydhondt** [comment]
4.1.1
